name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm generate
      - run: pnpm test run
      - run: pnpm build
      - name: Verify production build
        run: |
          pnpm preview &
          PREVIEW_PID=$!
          npx wait-on http://localhost:3000
          curl -sf http://localhost:3000
          kill $PREVIEW_PID
