name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      URL_CHECKS: |
        / 200
        /sitemap.xml 200
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm generate
      - run: pnpm test run
      - name: Verify production build
        run: |
          pnpm build
          node .output/server/index.mjs &
          PREVIEW_PID=$!
          trap "kill $PREVIEW_PID" EXIT
          npx wait-on http://localhost:3000
          while IFS= read -r line; do
            [ -z "$line" ] && continue
            set -- $line
            route=$1
            expected_status=$2
            shift 2
            expected_content="$*"
            tmpfile=$(mktemp)
            status=$(curl -s -o "$tmpfile" -w '%{http_code}' "http://localhost:3000$route")
            if [ "$status" != "$expected_status" ]; then
              echo "Unexpected status for $route: $status (expected $expected_status)"
              cat "$tmpfile"
              exit 1
            fi
            if [ -n "$expected_content" ] && ! grep -q "$expected_content" "$tmpfile"; then
              echo "Expected content not found for $route"
              cat "$tmpfile"
              exit 1
            fi
            rm "$tmpfile"
          done <<< "$URL_CHECKS"
