name: Deploy Static

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build static site
        run: pnpm generate

      - name: Build Storybook
        run: pnpm storybook:build

      - name: Prepare publish directory
        run: |
          cp CNAME dist/
          mkdir -p dist/storybook
          cp -r storybook-static/* dist/storybook/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
