name: Deploy Static

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CUSTOM_DOMAIN: "nudger.fr"   # ← mets ton domaine ou laisse vide

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build Nuxt static site
      - name: Build static site
        run: pnpm generate

      # Build Storybook
      - name: Build Storybook
        run: pnpm storybook:build

      # Prépare le dossier dist (copie propre de Nuxt)
      - name: Prepare dist folder
        run: |
          rm -rf dist              # supprime toute trace précédente
          cp -rT .output/public dist

      # Ajoute Storybook sous /storybook
      - name: Copy Storybook to dist/storybook
        run: |
          mkdir -p dist/storybook
          cp -r storybook-static/* dist/storybook/

      # Ajoute CNAME si domaine custom
      - name: Add CNAME file
        if: env.CUSTOM_DOMAIN != ''
        run: echo "${CUSTOM_DOMAIN}" > dist/CNAME

      # Déploiement GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
