name: Deploy Static

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CUSTOM_DOMAIN: "nudger.fr"

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Node + PNPM (choix explicite de la version Node → builds reproductibles)
      - uses: actions/setup-node@v4
        with:
          node-version: 20  # ou 18 LTS si besoin
          cache: "pnpm"

      - uses: pnpm/action-setup@v4

      # 3. Dépendances
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Build Nuxt (static) et Storybook
      - name: Build static site
        run: pnpm generate

      - name: Build Storybook
        run: pnpm storybook:build

      # 5. Prépare le dossier dist
      - name: Copy Nuxt output to dist
        run: |
          mkdir -p dist
          cp -r .output/public/* dist/

      - name: Copy Storybook to dist/storybook
        run: |
          mkdir -p dist/storybook
          cp -r storybook-static/* dist/storybook/

      # 6. Ajoute CNAME si domaine personnalisé
      - name: Add CNAME file
        if: env.CUSTOM_DOMAIN != ''
        run: echo "${CUSTOM_DOMAIN}" > dist/CNAME

      # 7. Déploiement GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Jekyll désactivé par défaut (.nojekyll auto-créé)
